CREATE TABLE articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(255) NOT NULL,
    source_article_id VARCHAR(255),
    title VARCHAR(1000) NOT NULL,
    url VARCHAR(2048) NOT NULL,
    canonical_url VARCHAR(2048),
    published_at TIMESTAMP WITH TIME ZONE,
    collected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    raw_content TEXT,
    cleaned_content TEXT,
    content_hash VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
