CREATE TABLE article_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    analysis_type VARCHAR(64) NOT NULL,
    analyzer_name VARCHAR(255) NOT NULL,
    analyzer_version VARCHAR(255) NOT NULL,
    analyzed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    text_sentiment VARCHAR(16) NOT NULL,
    positive_score FLOAT(53) NOT NULL,
    neutral_score FLOAT(53) NOT NULL,
    negative_score FLOAT(53) NOT NULL,
    confidence FLOAT(53) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_article_analyses_sentiment
        CHECK (text_sentiment IN ('positive', 'neutral', 'negative')),
    CONSTRAINT ck_article_analyses_positive_score
        CHECK (positive_score BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_article_analyses_neutral_score
        CHECK (neutral_score BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_article_analyses_negative_score
        CHECK (negative_score BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_article_analyses_confidence
        CHECK (confidence BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_article_analyses_score_sum
        CHECK (ABS(positive_score + neutral_score + negative_score - 1.0) <= 0.000001),
    CONSTRAINT uk_article_analyses_identity
        UNIQUE (article_id, analysis_type, analyzer_name, analyzer_version)
);

CREATE INDEX ix_article_analyses_article_analyzed_at
    ON article_analyses (article_id, analyzed_at DESC, id DESC);
