CREATE TABLE briefings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_version INTEGER NOT NULL,
    briefing_type VARCHAR(64) NOT NULL,
    payload TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_briefings_schema_version CHECK (schema_version > 0)
);

CREATE INDEX ix_briefings_created_at
    ON briefings (created_at DESC, id DESC);
